[package]
name = "vowlgrapher"
version = "0.0.1"
edition = "2024"
license = "MIT"


[lib]
crate-type = ["cdylib"]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
# https://doc.rust-lang.org/cargo/reference/profiles.html#lto
lto = "thin"

[features]
default = ["console_error_panic_hook"]

[dependencies]
# Web dev
wasm-pack = "0.13"
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1.7", optional = true }

# Graphs
grapher = "0.2.2"
petgraph = "0.6.5"
petgraph-gen = "0.1.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Misc
glam = "0.29.0"
glium = "0.33"
rand = "0.8.5"
winit = { version = "0.28.7" }
