[package]
name = "first_example"
version = "0.1.0"
edition = "2021"

[dependencies]
grapher = "0.2.2"
glam = "0.29.0"
glium = "0.33"
petgraph = "0.6.5"
petgraph-gen = "0.1.3"
rand = "0.8.5"
winit = { version = "0.28.7"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
